### ISSUE TITLE
rustc support?

### ISSUE THREAD

**Issue by wbrickner** [ccurtsinger/stabilizer#4]
Hello,

I'm wondering if I can get stabilizer to work with `cargo` / `rustc`?
If you're not familiar, `rustc` uses LLVM as a backend.
Looks like a very useful tool.

Thank you.

**Comment by Ten0** [comment]
+1. I'm looking to benchmark some rust code, and would benefit from stabilization.

**Comment by smr97** [comment]
Hey, me too! Any updates on this?

**Comment by magicaltoast** [comment]
+1

**Comment by wbrickner** [comment]
Haven't had a chance to try this yet, but this may work: [https://docs.rs/coz/0.1.3/coz/](https://docs.rs/coz/0.1.3/coz/).
Closing.

**Comment by somehowchris** [comment]
Interested too, well coz isn't stabilizer, it doesn't measure variance from what I know, any movement/still interested?
